#!/bin/bash

aws ec2 create-security-group --group-name teste --description "criacaoTeste" --vpc-id [vpc-XXXXXXXXXXXXX]


aws ec2 authorize-security-group-ingress --group-name teste --protocol tcp --port 22 --cidr 0.0.0.0/0

aws ec2 authorize-security-group-ingress --group-name teste --protocol tcp --port 80 --cidr 0.0.0.0/0

aws ec2 authorize-security-group-ingress --group-name teste --protocol tcp --port 443 --cidr 0.0.0.0/0

aws ec2 authorize-security-group-ingress --group-name teste --protocol tcp --port 111 --cidr 0.0.0.0/0

aws ec2 authorize-security-group-ingress --group-name teste --protocol udp --port 111 --cidr 0.0.0.0/0

aws ec2 authorize-security-group-ingress --group-name teste --protocol tcp --port 2049 --cidr 0.0.0.0/0

aws ec2 authorize-security-group-ingress --group-name teste --protocol udp --port 2049 --cidr 0.0.0.0/0
